name: Angular CI

on:
  push:
    branches: [main]
    paths: [src/angular-application/**]
  release:
    types: [published]

defaults:
  run:
    working-directory: ./src/angular-application

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://angular-web-app-basic.azurewebsites.net/
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ vars.AZURE_WEBAPP_PACKAGE_PATH }}
