name: Angular CI/CD

on:
  push:
    branches: [main]
  release:
      types: [published]

defaults:
  run:
    working-directory: ./src/angular-application

env:
  AZURE_WEBAPP_NAME: angular-web-app-basic
  AZURE_WEBAPP_PACKAGE_PATH: './src/angular-application/dist/angular-application/browser'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
